export const groups = [
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "bugbounty",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "bugbounty",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "bugbounty",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "bugbounty",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "bugbounty",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "bugbounty",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "Coders",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "codefeist",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
  {
    _id: "jslkjflfjoifwvw",
    name: "bugbounty",
    description: "this is a simple group",
    blogId: "jlgfd230fljdg4390hhd",
    admin: "837jhdklmvb7894503jhkdbn",
    moderators: ["shiva", "ramaiya", "arun"],
    members: ["ravi", "raj", "ramkumar"],
    joinRequests: ["person01", "person02", "person03"],
  },
];
export const joinRequests = [
  {
    user: "nvorvnfvejirtu437h4kjh76",
    group: "coders",
    status: "pending",
  },
  {
    user: "nvorvnfvejirtu437h4kjh76",
    group: "coders",
    status: "rejected",
  },
  {
    user: "nvorvnfvejirtu437h4kjh76",
    group: "codefeist",
    status: "rejected",
  },
  {
    user: "nvorvnfvejirtu437h4kjh76",
    group: "codefeist",
    status: "pending",
  },
  {
    user: "nvorvnfvejirtu437h4kjh76",
    group: "bugbounty",
    status: "pending",
  },
];
